testing pr (#26)
Co-authored-by: Nishu.Bharti1 <Nishu.Bharti1@ibm.com>

diff --git a/.pipeline-config.yaml b/.pipeline-config.yaml
--- a/.pipeline-config.yaml
+++ b/.pipeline-config.yaml
@@ -6,13 +6,26 @@ setup:
   image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.15
   script: |
     #!/usr/bin/env bash
-    PIPELINE_DEBUG="$(cat /config/PIPELINE_DEBUG)"
-    if [[ "$PIPELINE_DEBUG" == 1 ]]; then
-      trap env EXIT
-      env
-      set -x
+    cd ../"$(load_repo app-repo path)"
+    npm ci
+
+    # save exit code for old evidence collection
+    exit_code=0
+    npm test || exit_code=$?
+    
+    # save status for new evidence collection
+    status="success"
+    if [ "$exit_code" != "0" ]; then
+      status="failure"
     fi
-    echo "set up completed"
+
+    collect-evidence \
+      --tool-type "jest" \
+      --status "$status" \
+      --evidence-type "com.ibm.unit_tests" \
+      --asset-type "repo" \
+      --asset-key "app-repo"
+    exit $exit_code
 
 test:
   abort_on_failure: true
